language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27


sudo: false


before_install:
  - chmod +x gradlew
  - touch local.properties
  - yes | sdkmanager "platforms;android-27"
  

