language: android

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27

sudo: false

before_install:
  - touch local.properties
  - yes | sdkmanager "platforms;android-27"

script:
  - ./gradlew --no-daemon clean test -Pcoverage
